### ISSUE TITLE
Firejet bugs, compiled in one report for your convenience

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#22] opened 2020-02-13 00:58 UTC
**FireJet Hover bugs**
1. When you look directly at a block that is within range for mining, Hover will not activate.
2. When you press Shift with Hover activated, it doesn't end the Hover as it should.
3. If you continue to hold shift after Hover is activated, and then left-click, firejet will not activate. Instead you fall to the ground.
4. Firejet after using Hover seems unjustifiably long, almost as long as jetblaze. This destroys any advantage to using default firejet. (I think that Hover's primary uses should be 1. quick escape when you get surprise attacked and 2. an extra boost when jetting vertically upward)
5. Jetblast and Jetblaze cannot be activated from Hover

**Quasi-activation of Jetblast and Jetblaze during cooldown**
Jetblaze and Jetblast apparently activate (i.e, the cooldown, particles and sound effects are there), but they do not propel you into the air as they should. This bug only occurs if you try using jetblaze/jetblast immediately after using it previously, while it is still on cooldown. 

**Jetblaze damage and firetick are deactivated when changing slots**
When using Jetblaze, the damage and firetick (represented by the extra smoke and creeper noises) are deactivated. This bug occurs only when you switch to another slot while Jetblaze is running.

**General firejet bug**
A firebender should be able to end their firejet midair by left-clicking with the firejet slot but this does not work. This applies to all variations of Firejet (besides Hover, obviously).

**Comment by dniym** [comment] 2020-02-13 01:17
This really does not make it more convenient for Me this actually complicates it.  what it means is if I fix two of these issues and one is minor but not fixed then I can’t close this issue.  When you create an issue there’s a template it’s there for a reason so that all the relevant information is there for each issue so when I work on and fix it i can close the issue and *YOU* know I’ve worked on / fixed it.  


You have to physically delete the template to avoid using it so please create one bug report per bug so things can be marked fixed when they’re done.

**Closed as completed by dniym** 2020-02-13 01:17 UTC
Labels: invalid

**Comment by dovis-gif** [comment] 2020-02-13 01:36
darnit, you're really gonna make me rewrite everything? I didn't know that this would be inconvenient. Can I get a pass just this time? I won't do it again, and if something I mentioned here isn't working properly I can create a new issue for it as you said.

**Comment by dniym** [comment] 2020-02-13 01:50
Well cancelling firejets hover is working as intended because it would make no sense for shift click to be required to activate but only shift required to deactivate, so yeah at least one part of this is invalid, and it does completely complicate me being able to handle one issue at the time.

**Comment by dovis-gif** [comment] 2020-02-13 18:23
No, it makes perfect sense. That's exactly how Jed did it for fireski. The only reason why we have shift+click in the first place is to distinguish it from regular firejet. It does not necessarily follow that the cancellation should have the same inputs. 
Here's how it should work: Shift(added specifically for hover)+click activates Hover. Shift again will deactivate hover. Besides for that, mechanics are exactly the same as normal firejet : left-click once to activate normal jet, left click again to cancel it.
I think the problem is that you're thinking about this in an abstract way, instead of how the move is used in practice by players. This just makes it unnecessarily complicated.

**Comment by dovis-gif** [comment] 2020-02-13 18:27
Pleasepleaseplease just trust me on this stuff. I implore you to try fixing the bugs, then I'll test it. If something is still broken I'll create a new, separate report.

**Comment by dniym** [comment] 2020-02-13 20:24
I mean I get it you’ve got multiple things here that should be on multiple tickets.. fixing one thing here won’t fix them all, in the time it’s taken you to argue with me about creating a separate ticket per bug you could have separated them and I could be working on them already.   

It seems firejet hs multiple issues that need addressing and I’ll have to do them one at the time on my end, change the code, test and once it’s done move on.  the jetblaze/blast cooldown activating when the move is on cooldown has absolutely nothing to do with firejet and the fire tick when switching moves has nothing to do with either of the above issues.

**Comment by dovis-gif** [comment] 2020-02-13 20:42
Actually I think you're right. We could do things much more efficiently if you did the coding and I did the testing/reporting (in economics we call this "comparative advantage" :)) I'll repost the issues in multiple tickets. Sorry for inconveniencing you (I was trying to do the opposite).
